[package]
name = "parallel-disk-usage"
version = "0.0.0"
description = "Summarize disk usage of the set of files, recursively for directories"
authors = ["khai96_ <hvksmr1996@gmail.com>"]
edition = "2018"

[lib]
name = "parallel_disk_usage"
path = "src/lib.rs"

[[bin]]
name = "pdu"
path = "src/main.rs"

[[bin]]
name = "pdu-completions"
path = "src/completions.rs"

[dependencies]
pipe-trait = "^0.3.2"
structopt = "^0.3.21"
structopt-utilities = "^0.0.8"
smart-default = "^0.6.0"
derive_more = "^0.99.14"
rayon = "^1.5.0"
text-block-macros = "^0.1.1"
rounded-div = "^0.1.2"
fmt-iter = "^0.2.1"
itertools = "^0.10.0"
assert-cmp = "^0.2.0"
zero-copy-pads = "^0.2.0"
terminal_size = "^0.1.17"

[dependencies.strum]
version = "^0.20.0"
features = ["derive"]

[dev-dependencies]
build-fs-tree = "^0.2.6"
maplit = "^1.0.2"
pretty_assertions = "^0.7.2"
rand = "^0.8.3"
