name: Benchmark

on:
  - push
  - pull_request

jobs:
  competing_benchmark:
    name: Compare benchmark with similar tools

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2.1.5
        timeout-minutes: 1
        continue-on-error: true
        if: matrix.os != 'macos-latest' # Cache causes errors on macOS
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ github.job }}-Linux-${{ hashFiles('rust-toolchain') }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ github.job }}-Linux-${{ hashFiles('rust-toolchain') }}-${{ hashFiles('**/Cargo.lock') }}
            ${{ github.job }}-Linux-${{ hashFiles('rust-toolchain') }}-

      - name: Build pdu
        run: cargo build --release

      - name: Install dust
        run: cargo install du-dust --bin dust

      - name: Install dutree
        run: cargo install dutree --bin dutree

      - name: Modify $PATH
        run: |
          echo "$(pwd)/target/release" >> "$GITHUB_PATH"
          echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"

      - name: Inspect command locations
        run: |
          which pdu
          which dust
          which dutree
          which du

      - name: Warm up (CPU cache)
        continue-on-error: true
        run: |
          pdu --total-width 150 /usr >/dev/null 2>/dev/null &
          dust -w 150 /usr >/dev/null 2>/dev/null &
          dutree /usr >/dev/null 2>/dev/null &
          sh -c 'du /usr; true' >/dev/null 2>/dev/null &
          wait || true

      - name: 'Benchmark: len'
        env:
          BENCHMARK_IGNORE_FAILURE: 'true'
        run: |
          ./benchmark.sh pdu --total-width 150 /usr
          ./benchmark.sh dust -w 150 --apparent-size /usr
          ./benchmark.sh dutree /usr
          ./benchmark.sh du --apparent-size /usr

      - name: 'Benchmark: blksize'
        env:
          BENCHMARK_IGNORE_FAILURE: 'true'
        run: |
          ./benchmark.sh pdu --total-width 150 --quantity=blksize /usr
          ./benchmark.sh dust -w 150 /usr
          ./benchmark.sh dutree --usage /usr
          ./benchmark.sh du /usr

      - name: 'Benchmark: top-down'
        env:
          BENCHMARK_IGNORE_FAILURE: 'true'
        run: |
          ./benchmark.sh pdu --total-width 150 --top-down /usr
          ./benchmark.sh dust -w 150 --apparent-size --reverse /usr
          ./benchmark.sh dutree /usr

      - name: 'Benchmark: summary'
        env:
          BENCHMARK_IGNORE_FAILURE: 'true'
        run: |
          ./benchmark.sh pdu --total-width 150 --max-depth 1 /usr
          ./benchmark.sh dutree --summary /usr
          ./benchmark.sh du --apparent-size --total /usr
