name: Lint dependency graph

on:
  - push
  - pull_request

jobs:
  cargo_deny:
    name: Lint crate graph
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: EmbarkStudios/cargo-deny-action@v1.2.12
